/* Generated by Cython 0.25.2 */

#ifndef __PYX_HAVE__sam1
#define __PYX_HAVE__sam1


#ifndef __PYX_HAVE_API__sam1

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(double) calc(double, double);

#endif /* !__PYX_HAVE_API__sam1 */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initsam1(void);
#else
PyMODINIT_FUNC PyInit_sam1(void);
#endif

#endif /* !__PYX_HAVE__sam1 */
